#!/usr/bin/env bash
# Pre-deploy checks for Valheim.
#
# The world is generated by the server on first boot with a random seed, so
# there is nothing to stage. What this still guards is the join password: the
# image happily starts an UNPROTECTED server if SERVER_PASS is unset, and an
# open Valheim server on a forwarded port finds strangers quickly.
#
# It also warns, once, about the thing that is easy to get wrong later: the
# generated world is the only irreplaceable state on the box and it is NOT in
# git.
#
# Run from anywhere:  bash games/valheim/preflight.sh
set -euo pipefail
cd "$(dirname "$0")"

WORLD_NAME="$(grep -E '^WORLD_NAME=' game.env | head -1 | cut -d= -f2-)"
DATA_DIR="$(grep -E '^DATA_DIR=' stack.env | head -1 | cut -d= -f2-)"
WORLDS="${DATA_DIR%/}/config/worlds_local"

echo "==> Valheim preflight"
echo "    world name : ${WORLD_NAME}"

fail=0

# ── join password ────────────────────────────────────────────────────────────
# Valheim rejects a password under 5 characters, and rejects one that appears
# inside the server name or the world name — both are silent-ish failures that
# leave you with a server nobody can join, so check them here.
if [ -f game.local.env ] && grep -qE '^SERVER_PASS=.+' game.local.env; then
  pass="$(grep -E '^SERVER_PASS=' game.local.env | head -1 | cut -d= -f2-)"
  server_name="$(grep -E '^SERVER_NAME=' game.env | head -1 | cut -d= -f2-)"
  echo "    password   : set in game.local.env (${#pass} characters)"
  if [ "${#pass}" -lt 5 ]; then
    echo "    ERROR      : Valheim requires at least 5 characters" >&2
    fail=1
  fi
  # Case-insensitive on purpose: Valheim's own check is stricter than people
  # expect, and a guard that only catches the exact case is worse than useless
  # because it reads as a pass. Nothing below ever prints the password itself.
  lpass="${pass,,}"
  for field in SERVER_NAME:"$server_name" WORLD_NAME:"$WORLD_NAME"; do
    label="${field%%:*}"; value="${field#*:}"
    # Lowercase FIRST, into its own variable. ${value,,//x/} does not chain the
    # two expansions - it misparses, and the guard silently inverts.
    lvalue="${value,,}"
    if [ -n "$lpass" ] && [ "$lvalue" != "${lvalue//$lpass/}" ]; then
      echo "    ERROR      : the password appears inside ${label} (\"${value}\")." >&2
      echo "                 Valheim refuses to start in that case." >&2
      echo "                 SERVER_NAME follows the RageQuit-<Game> convention" >&2
      echo "                 and WORLD_NAME names an existing save, so the thing" >&2
      echo "                 to change is the PASSWORD in game.local.env." >&2
      fail=1
    fi
  done
else
  cat >&2 <<'EOS'
    ERROR      : no join password.

                 Create games/valheim/game.local.env (gitignored) with:
                     SERVER_PASS=your-password-here
                 At least 5 characters, and it must not appear inside the
                 server name or the world name.

                 Without it the server starts OPEN. Unlike 7DTD there is no
                 fallback to Palworld's password - this image reads SERVER_PASS
                 only from its own env files.
EOS
  fail=1
fi

# ── world state ──────────────────────────────────────────────────────────────
if [ -f "${WORLDS}/${WORLD_NAME}.db" ]; then
  echo "    world      : exists already - this deploy will KEEP it"
  printf '                 %s (%s bytes)\n' "${WORLDS}/${WORLD_NAME}.db" \
    "$(stat -c%s "${WORLDS}/${WORLD_NAME}.db" 2>/dev/null || stat -f%z "${WORLDS}/${WORLD_NAME}.db")"
else
  echo "    world      : none yet - the server will GENERATE one on first boot"
  echo "                 with a random seed. That world then becomes the only"
  echo "                 irreplaceable state here and it is NOT in git."
  echo "                 Back up ${WORLDS} once it exists."
fi

if [ "$fail" -ne 0 ]; then
  echo >&2
  echo "NOT READY TO DEPLOY - fix the errors above and re-run." >&2
  exit 1
fi

echo "==> OK - safe to run ./scripts/deploy.sh valheim"
